-- Drop the table if it exists
DROP TABLE IF EXISTS store;
DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS timesheet;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS cones;
DROP TABLE IF EXISTS ice_cream;

CREATE TABLE store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location VARCHAR
);
-- Create store Table
CREATE TABLE ice_cream (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flavor VARCHAR, 
  dairy_free BOOLEAN, 
  quantity BIGINT,
  price BIGINT
);
CREATE TABLE customer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR, 
  purchases BIGINT
);

CREATE TABLE cones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cone_type VARCHAR,
  gluten_free BOOLEAN,
  quantity BIGINT,
  price BIGINT
);

CREATE TABLE sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profit BIGINT
);

CREATE TABLE inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE timesheet (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hours BIGINT
);


CREATE TABLE employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR,
  position VARCHAR
);
-- Add foreign key constraints for employees table
ALTER TABLE employees ADD CONSTRAINT fk_employees_store FOREIGN KEY (store_id) REFERENCES store(id);

-- Add foreign key constraints for sales table
ALTER TABLE sales ADD CONSTRAINT fk_sales_customer FOREIGN KEY (customer_id) REFERENCES customer(id);

-- Add foreign key constraints for inventory table
ALTER TABLE inventory ADD CONSTRAINT fk_inventory_ice_cream FOREIGN KEY (ice_cream_id) REFERENCES ice_cream(id);
ALTER TABLE inventory ADD CONSTRAINT fk_inventory_cones FOREIGN KEY (cones_id) REFERENCES cones(id);

-- Add foreign key constraints for timesheet table
ALTER TABLE timesheet ADD CONSTRAINT fk_timesheet_employee FOREIGN KEY (employee_id) REFERENCES employees(id);

-- Add foreign key constraints for store table
ALTER TABLE store ADD CONSTRAINT fk_store_employee FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE store ADD CONSTRAINT fk_store_inventory FOREIGN KEY (inventory_id) REFERENCES inventory(id);
ALTER TABLE store ADD CONSTRAINT fk_store_sales FOREIGN KEY (sales_id) REFERENCES sales(id);


\COPY store FROM 'store.csv' WITH CSV HEADER;
\COPY cones FROM 'cones.csv' WITH CSV HEADER;
\COPY customer FROM 'customer.csv' WITH CSV HEADER;
\COPY employee FROM 'employees.csv' WITH CSV HEADER;
\COPY ice_cream FROM 'ice_cream.csv' WITH CSV HEADER;
\COPY inventory FROM 'inventory.csv' WITH CSV HEADER;
\COPY sales FROM 'sales.csv' WITH CSV HEADER;
\COPY timesheet FROM 'timesheet.csv' WITH CSV HEADER;

